/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh
    Plane001: THREE.Mesh
    Plane002: THREE.Mesh
    Plane003: THREE.Mesh
    Plane004: THREE.Mesh
    mask: THREE.Mesh
    leaf4: THREE.Mesh
    leaf4001: THREE.Mesh
    leaf4002: THREE.Mesh
    leaf4003: THREE.Mesh
    leaf4004: THREE.Mesh
    leaf4005: THREE.Mesh
    leaf4006: THREE.Mesh
    leaf4007: THREE.Mesh
    leaf4008: THREE.Mesh
    leaf4009: THREE.Mesh
    leaf4010: THREE.Mesh
    leaf4011: THREE.Mesh
    leaf4012: THREE.Mesh
    leaf4013: THREE.Mesh
    leaf4014: THREE.Mesh
    leaf4015: THREE.Mesh
    leaf4016: THREE.Mesh
    leaf4017: THREE.Mesh
    leaf4018: THREE.Mesh
    leaf4019: THREE.Mesh
    leaf4020: THREE.Mesh
    leaf4021: THREE.Mesh
    leaf4022: THREE.Mesh
    leaf4023: THREE.Mesh
    leaf4024: THREE.Mesh
    leaf4025: THREE.Mesh
    leaf4026: THREE.Mesh
    leaf4027: THREE.Mesh
    leaf4028: THREE.Mesh
    leaf4029: THREE.Mesh
    leaf4030: THREE.Mesh
    leaf4031: THREE.Mesh
    leaf4032: THREE.Mesh
    leaf4033: THREE.Mesh
    leaf4034: THREE.Mesh
    leaf4035: THREE.Mesh
    leaf4036: THREE.Mesh
    leaf4037: THREE.Mesh
    leaf4038: THREE.Mesh
    leaf4039: THREE.Mesh
    leaf4040: THREE.Mesh
    leaf4041: THREE.Mesh
    leaf4042: THREE.Mesh
    leaf4043: THREE.Mesh
    trunk: THREE.Mesh
    trunk001: THREE.Mesh
    trunk002: THREE.Mesh
    trunk003: THREE.Mesh
    trunk004: THREE.Mesh
    trunk005: THREE.Mesh
    trunk006: THREE.Mesh
    trunk007: THREE.Mesh
    trunk008: THREE.Mesh
    trunk009: THREE.Mesh
    trunk010: THREE.Mesh
    trunk011: THREE.Mesh
    trunk012: THREE.Mesh
    trunk013: THREE.Mesh
    trunk014: THREE.Mesh
    trunk015: THREE.Mesh
    trunk016: THREE.Mesh
    trunk017: THREE.Mesh
    trunk018: THREE.Mesh
    trunk019: THREE.Mesh
    trunk020: THREE.Mesh
    trunk021: THREE.Mesh
    trunk022: THREE.Mesh
    trunk023: THREE.Mesh
    trunk024: THREE.Mesh
    trunk025: THREE.Mesh
    trunk026: THREE.Mesh
    trunk027: THREE.Mesh
    trunk028: THREE.Mesh
    trunk029: THREE.Mesh
    trunk030: THREE.Mesh
    trunk031: THREE.Mesh
    trunk032: THREE.Mesh
    trunk033: THREE.Mesh
    trunk034: THREE.Mesh
    trunk035: THREE.Mesh
    trunk036: THREE.Mesh
    trunk037: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTF('/environment.glb') as unknown as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes.Plane.geometry} material={nodes.Plane.material} scale={100} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={nodes.Plane001.material}
        position={[0, 0, 4.84]}
        rotation={[-0.07, 0.01, -0.07]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={nodes.Plane002.material}
        position={[30.76, 1.62, -9.04]}
        rotation={[0.03, -0.27, 0.04]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={nodes.Plane003.material}
        position={[-39.19, 2.27, -74.4]}
        rotation={[-0.02, 0.19, -0.17]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={nodes.Plane004.material}
        position={[-8.25, 1.62, -80.25]}
        rotation={[0.1, 0.31, 0.2]}
        scale={100}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mask.geometry}
        material={nodes.mask.material}
        position={[0, 2.66, -8.81]}
        scale={[4.39, 1, 3.14]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4.geometry}
        material={nodes.leaf4.material}
        position={[1.73, 3.82, -23.89]}
        rotation={[0.01, -0.52, 0.3]}
        scale={[1.59, 1.11, 1.11]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4001.geometry}
        material={nodes.leaf4001.material}
        position={[4.87, 4.37, -27.35]}
        rotation={[0.01, -0.52, 0.3]}
        scale={[1.03, 0.72, 0.72]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4002.geometry}
        material={nodes.leaf4002.material}
        position={[-4.64, 2.65, -51.9]}
        rotation={[0.01, -0.52, 0.3]}
        scale={[1.03, 0.72, 0.72]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4003.geometry}
        material={nodes.leaf4003.material}
        position={[-26.94, 3.5, -51.9]}
        rotation={[-0.06, -0.56, 0.19]}
        scale={[1.03, 0.72, 0.72]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4004.geometry}
        material={nodes.leaf4004.material}
        position={[-21.97, 3.19, -45.68]}
        rotation={[-0.06, -0.56, 0.19]}
        scale={[1.03, 0.72, 0.72]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4005.geometry}
        material={nodes.leaf4005.material}
        position={[-14.07, 3.64, -24.82]}
        rotation={[0.01, 0.5, -0.38]}
        scale={[-1.46, 1.02, 1.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4006.geometry}
        material={nodes.leaf4006.material}
        position={[18.9, 12.48, -81.62]}
        rotation={[-0.05, 0.55, -0.22]}
        scale={[-1.46, 1.02, 1.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4007.geometry}
        material={nodes.leaf4007.material}
        position={[24.97, 13.54, -82.91]}
        rotation={[0.02, 0.49, -0.4]}
        scale={[-1.46, 1.02, 1.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4008.geometry}
        material={nodes.leaf4008.material}
        position={[0.27, 14.22, -109.25]}
        rotation={[-0.02, 0.53, -0.29]}
        scale={[-1.46, 1.02, 1.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4009.geometry}
        material={nodes.leaf4009.material}
        position={[7.83, 3.89, -18.17]}
        rotation={[0.01, -0.52, 0.3]}
        scale={[0.97, 0.67, 0.67]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4010.geometry}
        material={nodes.leaf4010.material}
        position={[10.91, 5.06, -43.25]}
        rotation={[0.01, -0.52, 0.3]}
        scale={[1.59, 1.1, 1.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4011.geometry}
        material={nodes.leaf4011.material}
        position={[20.93, 5.55, -35.66]}
        rotation={[0.01, -0.52, 0.3]}
        scale={[1.87, 1.3, 1.3]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4012.geometry}
        material={nodes.leaf4012.material}
        position={[22.06, 11.09, -81.29]}
        rotation={[-0.05, 0.55, -0.22]}
        scale={[-1.46, 1.02, 1.02]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4013.geometry}
        material={nodes.leaf4013.material}
        position={[14.03, 8.45, -44.12]}
        rotation={[0.01, 0.52, -0.3]}
        scale={[-2.2, 1.53, 1.53]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4014.geometry}
        material={nodes.leaf4014.material}
        position={[1.36, 7.57, -87.82]}
        rotation={[-0.05, 0.54, -0.28]}
        scale={[-1, 0.7, 0.7]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4015.geometry}
        material={nodes.leaf4015.material}
        position={[2.94, 6.73, -77.72]}
        rotation={[-0.05, 0.55, -0.22]}
        scale={[-1, 0.7, 0.7]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4016.geometry}
        material={nodes.leaf4016.material}
        position={[3.32, 4.13, -41.45]}
        rotation={[0.01, -0.52, 0.3]}
        scale={[1.59, 1.1, 1.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4017.geometry}
        material={nodes.leaf4017.material}
        position={[-38.27, 3.45, -87.14]}
        rotation={[-0.21, -0.1, 0.26]}
        scale={[1.03, 0.72, 0.72]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4018.geometry}
        material={nodes.leaf4018.material}
        position={[-30.19, 1.44, -87.63]}
        rotation={[-0.21, -0.1, 0.26]}
        scale={[1.03, 0.72, 0.72]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4019.geometry}
        material={nodes.leaf4019.material}
        position={[16.79, 5.42, -43.96]}
        rotation={[0.01, -0.52, 0.3]}
        scale={[1.59, 1.1, 1.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4020.geometry}
        material={nodes.leaf4020.material}
        position={[1.73, 0.8, -29.54]}
        rotation={[0.03, 0.14, 0.39]}
        scale={[0.85, 0.8, 0.56]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4021.geometry}
        material={nodes.leaf4021.material}
        position={[-13.19, 3.5, -83.48]}
        rotation={[-0.15, -0.08, 0.33]}
        scale={[0.79, 0.55, 0.55]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4022.geometry}
        material={nodes.leaf4022.material}
        position={[-11.14, 3.16, -84.17]}
        rotation={[-0.15, -0.08, 0.33]}
        scale={[0.79, 0.55, 0.55]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4023.geometry}
        material={nodes.leaf4023.material}
        position={[12.53, 1.12, -34.06]}
        rotation={[0.03, 0.14, 0.39]}
        scale={[0.85, 0.8, 0.56]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4024.geometry}
        material={nodes.leaf4024.material}
        position={[13.56, 1.18, -34.47]}
        rotation={[0.06, 0.94, 0.35]}
        scale={[0.85, 0.8, 0.56]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4025.geometry}
        material={nodes.leaf4025.material}
        position={[17.11, 1.32, -35.97]}
        rotation={[0.06, 0.94, 0.35]}
        scale={[0.54, 0.51, 0.36]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4026.geometry}
        material={nodes.leaf4026.material}
        position={[5.13, 0.78, -19.31]}
        rotation={[0.03, 0.14, 0.39]}
        scale={[0.9, 0.85, 0.6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4027.geometry}
        material={nodes.leaf4027.material}
        position={[6.21, 0.84, -19.75]}
        rotation={[0.06, 0.94, 0.35]}
        scale={[0.9, 0.85, 0.6]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4028.geometry}
        material={nodes.leaf4028.material}
        position={[24.21, 6.98, -39.74]}
        rotation={[0.01, -0.52, 0.3]}
        scale={[1.99, 1.38, 1.38]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4029.geometry}
        material={nodes.leaf4029.material}
        position={[31.76, 12.7, -64.45]}
        rotation={[0.01, -0.52, 0.3]}
        scale={[0.76, 0.53, 0.53]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4030.geometry}
        material={nodes.leaf4030.material}
        position={[34.19, 13.6, -65.64]}
        rotation={[0.2, -0.46, 0.52]}
        scale={[0.76, 0.53, 0.53]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4031.geometry}
        material={nodes.leaf4031.material}
        position={[35.79, 13.17, -66.3]}
        rotation={[0.2, -0.46, 0.52]}
        scale={[0.5, 0.35, 0.35]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4032.geometry}
        material={nodes.leaf4032.material}
        position={[37.25, 13.44, -67.19]}
        rotation={[0.2, -0.46, 0.52]}
        scale={[0.39, 0.27, 0.27]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4033.geometry}
        material={nodes.leaf4033.material}
        position={[38.59, 13.44, -67.75]}
        rotation={[0.2, -0.46, 0.52]}
        scale={[0.39, 0.27, 0.27]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4034.geometry}
        material={nodes.leaf4034.material}
        position={[33.68, 11.17, -60.23]}
        rotation={[0.06, -0.51, 0.36]}
        scale={[0.97, 0.68, 0.68]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4035.geometry}
        material={nodes.leaf4035.material}
        position={[35.84, 11.76, -61.24]}
        rotation={[0.06, -0.51, 0.36]}
        scale={[0.97, 0.68, 0.68]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4036.geometry}
        material={nodes.leaf4036.material}
        position={[25.54, 9.95, -52.82]}
        rotation={[0.01, -0.52, 0.31]}
        scale={[1.63, 1.13, 1.13]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4037.geometry}
        material={nodes.leaf4037.material}
        position={[30.75, 12.23, -50.48]}
        rotation={[0.01, -0.52, 0.3]}
        scale={[1.59, 1.1, 1.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4038.geometry}
        material={nodes.leaf4038.material}
        position={[19.8, 9.4, -64.37]}
        rotation={[0.01, -0.52, 0.3]}
        scale={[1.59, 1.1, 1.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4039.geometry}
        material={nodes.leaf4039.material}
        position={[-23.95, 6.82, -50.48]}
        rotation={[0.01, -0.52, 0.3]}
        scale={[1.59, 1.1, 1.1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4040.geometry}
        material={nodes.leaf4040.material}
        position={[-8.14, 5.12, -77.66]}
        rotation={[0.01, -0.52, 0.3]}
        scale={[0.97, 0.67, 0.67]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4041.geometry}
        material={nodes.leaf4041.material}
        position={[-29.73, 5.12, -77.66]}
        rotation={[0.01, -0.52, 0.3]}
        scale={[0.97, 0.67, 0.67]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4042.geometry}
        material={nodes.leaf4042.material}
        position={[8.73, 8.4, -84.17]}
        rotation={[-0.15, -0.08, 0.33]}
        scale={[0.79, 0.55, 0.55]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.leaf4043.geometry}
        material={nodes.leaf4043.material}
        position={[7.68, 3.89, -42.03]}
        rotation={[0.01, 0.14, 0.3]}
        scale={[0.97, 0.67, 0.67]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk.geometry}
        material={nodes.trunk.material}
        position={[0, 0.39, -23.7]}
        scale={[0.57, 2.27, 0.57]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk001.geometry}
        material={nodes.trunk001.material}
        position={[3.76, 2.16, -27.23]}
        scale={[0.37, 1.47, 0.37]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk002.geometry}
        material={nodes.trunk002.material}
        position={[-5.76, 0.43, -51.78]}
        scale={[0.37, 1.47, 0.37]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk003.geometry}
        material={nodes.trunk003.material}
        position={[-28.27, 1.4, -51.79]}
        rotation={[-0.02, -0.03, -0.1]}
        scale={[0.37, 1.47, 0.37]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk004.geometry}
        material={nodes.trunk004.material}
        position={[-23.3, 1.09, -45.57]}
        rotation={[-0.02, -0.03, -0.1]}
        scale={[0.37, 1.47, 0.37]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk005.geometry}
        material={nodes.trunk005.material}
        position={[-12.7, 0.41, -24.5]}
        rotation={[-0.04, -0.02, -0.07]}
        scale={[-0.52, 2.08, 0.52]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk006.geometry}
        material={nodes.trunk006.material}
        position={[20.7, 9.46, -81.43]}
        rotation={[-0.02, 0.03, 0.07]}
        scale={[-0.52, 2.08, 0.52]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk007.geometry}
        material={nodes.trunk007.material}
        position={[26.29, 10.29, -82.57]}
        rotation={[-0.04, -0.03, -0.08]}
        scale={[-0.52, 2.08, 0.52]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk008.geometry}
        material={nodes.trunk008.material}
        position={[1.88, 11.09, -109]}
        rotation={[-0.03, 0, 0.01]}
        scale={[-0.52, 2.08, 0.52]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk009.geometry}
        material={nodes.trunk009.material}
        position={[6.78, 1.81, -18.06]}
        scale={[0.35, 1.37, 0.35]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk010.geometry}
        material={nodes.trunk010.material}
        position={[9.19, 1.64, -43.06]}
        scale={[0.57, 2.26, 0.57]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk011.geometry}
        material={nodes.trunk011.material}
        position={[18.9, 1.53, -35.44]}
        scale={[0.67, 2.66, 0.67]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk012.geometry}
        material={nodes.trunk012.material}
        position={[23.86, 8.06, -81.1]}
        rotation={[-0.02, 0.03, 0.07]}
        scale={[-0.52, 2.08, 0.52]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk013.geometry}
        material={nodes.trunk013.material}
        position={[16.42, 3.71, -43.86]}
        scale={[-0.79, 3.14, 0.79]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk014.geometry}
        material={nodes.trunk014.material}
        position={[2.48, 5.44, -87.6]}
        rotation={[-0.05, 0.01, 0.01]}
        scale={[-0.36, 1.43, 0.36]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk015.geometry}
        material={nodes.trunk015.material}
        position={[4.18, 4.65, -77.6]}
        rotation={[-0.02, 0.03, 0.07]}
        scale={[-0.36, 1.43, 0.36]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk016.geometry}
        material={nodes.trunk016.material}
        position={[1.6, 0.71, -41.26]}
        scale={[0.57, 2.26, 0.57]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk017.geometry}
        material={nodes.trunk017.material}
        position={[-39.34, 1.44, -86.13]}
        rotation={[-0.19, 0.42, -0.05]}
        scale={[0.37, 1.47, 0.37]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk018.geometry}
        material={nodes.trunk018.material}
        position={[-31.25, -0.56, -86.63]}
        rotation={[-0.19, 0.42, -0.05]}
        scale={[0.37, 1.47, 0.37]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk019.geometry}
        material={nodes.trunk019.material}
        position={[15.07, 2.01, -43.77]}
        scale={[0.57, 2.26, 0.57]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk020.geometry}
        material={nodes.trunk020.material}
        position={[-13.86, 1.88, -82.75]}
        rotation={[-0.18, 0.45, 0.04]}
        scale={[0.28, 1.13, 0.28]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk021.geometry}
        material={nodes.trunk021.material}
        position={[-11.82, 1.53, -83.44]}
        rotation={[-0.18, 0.45, 0.04]}
        scale={[0.28, 1.13, 0.28]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk022.geometry}
        material={nodes.trunk022.material}
        position={[22.05, 2.7, -39.5]}
        scale={[0.71, 2.83, 0.71]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk023.geometry}
        material={nodes.trunk023.material}
        position={[30.94, 11.08, -64.36]}
        scale={[0.27, 1.07, 0.27]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk024.geometry}
        material={nodes.trunk024.material}
        position={[33.71, 11.85, -65.66]}
        rotation={[0.08, 0.05, 0.2]}
        scale={[0.27, 1.07, 0.27]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk025.geometry}
        material={nodes.trunk025.material}
        position={[35.47, 12, -66.32]}
        rotation={[0.08, 0.05, 0.2]}
        scale={[0.18, 0.72, 0.18]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk026.geometry}
        material={nodes.trunk026.material}
        position={[37, 12.53, -67.21]}
        rotation={[0.08, 0.05, 0.2]}
        scale={[0.14, 0.56, 0.14]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk027.geometry}
        material={nodes.trunk027.material}
        position={[38.34, 12.53, -67.76]}
        rotation={[0.08, 0.05, 0.2]}
        scale={[0.14, 0.56, 0.14]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk028.geometry}
        material={nodes.trunk028.material}
        position={[32.74, 9.02, -60.15]}
        rotation={[0.02, 0.01, 0.05]}
        scale={[0.35, 1.39, 0.35]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk029.geometry}
        material={nodes.trunk029.material}
        position={[34.9, 9.61, -61.16]}
        rotation={[0.02, 0.01, 0.05]}
        scale={[0.35, 1.39, 0.35]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk030.geometry}
        material={nodes.trunk030.material}
        position={[23.79, 6.45, -52.63]}
        scale={[0.58, 2.32, 0.58]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk031.geometry}
        material={nodes.trunk031.material}
        position={[29.03, 8.82, -50.29]}
        scale={[0.57, 2.26, 0.57]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk032.geometry}
        material={nodes.trunk032.material}
        position={[18.08, 5.99, -64.18]}
        scale={[0.57, 2.26, 0.57]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk033.geometry}
        material={nodes.trunk033.material}
        position={[-25.67, 3.4, -50.29]}
        scale={[0.57, 2.26, 0.57]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk034.geometry}
        material={nodes.trunk034.material}
        position={[-9.19, 3.04, -77.55]}
        scale={[0.35, 1.37, 0.35]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk035.geometry}
        material={nodes.trunk035.material}
        position={[-30.78, 3.04, -77.55]}
        scale={[0.35, 1.37, 0.35]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk036.geometry}
        material={nodes.trunk036.material}
        position={[8.05, 6.77, -83.44]}
        rotation={[-0.18, 0.45, 0.04]}
        scale={[0.28, 1.13, 0.28]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.trunk037.geometry}
        material={nodes.trunk037.material}
        position={[6.93, 1.81, -41.3]}
        rotation={[0, 0.67, 0]}
        scale={[0.35, 1.37, 0.35]}
      />
    </group>
  )
}

useGLTF.preload('/environment.glb')
