import { ContactShadows } from '@react-three/drei'
import { Canvas } from '@react-three/fiber'
import { Bloom, EffectComposer, Noise } from '@react-three/postprocessing'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Suspense } from 'react'

import EnvironmentModel from '../components/EnvironmentModel/Environment'
import Plant from '../components/Plant/Testplant'

import styles from '../styles/Environment.module.css'

const Environment: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Plantyy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <div className={styles.graphic}>
            <Canvas
                camera={{ fov: 75, near: 0.1, far: 1000, position: [0, 3, 7] }} 
                dpr={[1, 2]}
                flat={true}
            >

            <Suspense fallback={(<span>Loading...</span>)}>

                <EnvironmentModel castShadow />

                </Suspense>
                {/* <Plant></Plant> */}

                <ContactShadows
                    frames={10}
                    position={[0, -1.05, 0]}
                    scale={10}
                    blur={10}
                    far={1.2}
                    />
                    

                <EffectComposer>
                    <Bloom luminanceThreshold={2} luminanceSmoothing={1.9} height={600} />
                    <Noise opacity={0.1} premultiply />
                </EffectComposer>
            </Canvas>
        </div>        
    </div>
  )
}

export default Environment
