import type { NextPage } from 'next'
import Head from 'next/head'

import {Plant} from '../components/Plant/Plant'

import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.wrapper}>
      <div className={styles.container}>
        <Head>
          <title>Plantsy</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
          <link href="https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap" rel="stylesheet"/>
        </Head>

        <section className={styles.hero}>

          <h1 className={styles.title}>
            Grow your own&nbsp;
            <span className={styles.highlight}>favourite</span>
            &nbsp;plant
          </h1>

          <div className={styles.graphic}>  
            <Plant></Plant>
          </div>

        </section>
      </div>  
    </div>
  )
}

export default Home
