import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

import { Plant } from '../components/Plant/Plant'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <h1 className={styles.title}>
          Grow your own&nbsp;
          <span className={styles.highlight}>favourite</span>
          &nbsp;plant
        </h1>

        <Plant></Plant>

        
    </div>
  )
}

export default Home
